export class Texts {
  home() {
    return {
      TAB_ONE_TEXT: {
        URL_HOME: "http://sampleapp.tricentis.com/101/app.php",
        URL_PARCIAL: "sampleapp.tricentis",
        VEHICLE_INSURANCE: "Vehicle Insurance Application",
        THIS_IS_A_SAMPLE: "This is a sample application, Version 1.0.1",
        VISIT_SUPPORT_BUTTON: " Visit Support!",
        AUTOMOBILE_BUTTON: "Automobile",
        TRUCK_BUTTON: "Truck",
        MOTORCYCLE_BUTTON: "Motorcycle",
        CAMPER_BUTTON: "Camper",
        REQUEST_BUTTON: "Request Demo",
        HOME_BUTTON: "Home",
        UNDEFINED_INSURANCE_TEXT: "undefined Insurance",
        ENTER_VEHICLE: "Enter Vehicle Data12",
        ENTER_INSURANT: "Enter Insurant Data7",
        ENTER_PRODUCT: "Enter Product Data6",
        SELECT_PRICE: "Select Price Option1",
        SED_QUOTE: "Send Quote4",
        MAKE_OPTION: "BMW",
        MODEL_OPTION: "Motorcycle",
        CYLINDER_CAPACITY: "200",
        ENGINE_PERFORMANCE: "512",
        DATE: "10/26/2017",
        NUMBER_OF_SEATS_OPTION: "2",
        NUMBER_OF_SEATS_SECOND_OPTION: "2",
        FUEL_TIPE_OPTION: "Diesel",
        PLAYLOAD: "500",
        TOTAL_WEIGHT: "1500",
        LIST_PRICE: "20000",
        LICENSE_PLATE_NUMBER: "KGKH-10024",
        ANNUAL_MILEAHE: "30000",
        BUTTON_NEXT: "Next »",
        ABOUT_BUTTON: "About",
        PRODUCTS_BUTTON: "Products",
        EVENTS_BUTTON: "Events & Webinars",
        RESOURCES_BUTTON: "Resources",
        SERVICES_BUTTON: "Services",
        COPYRIHT: "Copyright 2021 by Tricentis GmbH. All rights reserved.",
      },
      TAB_TWO_TEXT: {
        FIRST_NAME: "Victor",
        LAST_NAME: "Fernandes",
        DATE_OF_BIRTH: "01/19/1992",
        STREET_ADDRESS: "200, Olivia Alves De Luna",
        COUNTRY: "Brazil",
        ZIPCODE: "58449000",
        CITY: "Campina Grande",
        LABEL_ZIPCODE: "Zip Code",
        LABEL_CITY: "City",
        LABEL_GENDER: "Gender",
        LABEL_WEBSITE: "Website",
        OCCUPATION: "Employee",
        WEBSITE: "google.com",
        BUTTON_NEXT_PRODUCT_DATA: "#nextenterproductdata",
      },
      TAB_THREE_TEXT: {
        START_DATE: "03/30/2023",
        INSURANCE_SUM: "3.000.000,00",
        MERIT_RATING: "Bonus 3",
        DAMAGE_INSURANCE: "No Coverage",
        COURTESY_CAR: "No",
        LABEL_COURTESY_CAR: "Courtesy Car",
        LABEL_DAMAGE_INSURANCE: "Damage Insurance",
        LABEL_MERIT_RATING: "Merit Rating",
        LABEL_START_DATE: "Start Date",
      },
      TAB_FOUR_TEXT: {
        LABEL_ULTIMATE: "Ultimate",
        LABEL_PLATINUM: "Platinum",
        LABEL_GOLD: "Gold",
        LABEL_SILVER: "Silver",
      },
      TAB_FIVE_TEXT: {
        EMAIL: "huggofernandes@hotmail.com",
        PHONE: "83996248841",
        USERNAME: "victorsiqueira",
        PASSWORD: "Teste123@",
        CONFIRM_PASSWORD: "Teste123@",
        COMMENTS: "teste teste teste",
        LABEL_EMAIL: "E-Mail",
        LABEL_PASSWORD: "Password",
        LABEL_USERNAME: "Username",
        LABEL_PHONE: "Phone",
        LABEL_SUCCESS: "Sending e-mail success!"
      },
    };
  }
}
const texts = new Texts();
export default texts;
